[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::ResourceWarning
    ignore:StarletteDeprecationWarning
    ignore::sqlalchemy.exc.SAWarning
    ignore::pytest.PytestUnraisableExceptionWarning
